// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non transaction-pooled) connection. On Supabase
    // that is the "Session pooler" or "Direct connection" string. At runtime the
    // app uses DATABASE_URL, which can point at the transaction pooler (:6543).
    // `||` (not `??`) so an empty DIRECT_DATABASE_URL still falls back.
    url: process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
